# Set global options
data_dir = "/mia/vector-config/data"

[sources.in]
    type = "stdin"

[sinks.out]
    inputs = ["in"]
    type = "console"

[sinks.tcp]
    inputs = ["in"]
    type = "tcp"
    address = "127.0.0.1:1337"

[sinks.tcp.buffer]

  inputs = ["in"]

# The buffer's type / location. `disk` buffers are persistent and will be
# retained between restarts.
#
  # * optional
  # * default: "memory"
  # * enum: "memory" or "disk"
  # type = "memory"
  type = "disk"

  # The behavior when the buffer becomes full.
  #
  # * optional
  # * default: "block"
  # * enum: "block" or "drop_newest"
  # when_full = "block"
  when_full = "drop_newest"

  # The maximum size of the buffer on the disk.
  #
  # * optional
  # * no default
  # * unit: bytes
  max_size = 104900000

  # The maximum number of events allowed in the buffer.
  #
  # * optional
  # * default: 500
  # * unit: events
  num_items = 500

[sinks.backups]
  type = "tcp"
  address = "127.0.0.1:6379"
  inputs = ["in"]

[sinks.backups.buffer]
  type = "disk"
  max_size = 5000000000 # 5gb
  when_full = "block"
