# Set global options
data_dir = "/mia/vector-config/data"

[sources.in]
    type = "stdin"

# Ingest data by tailing one or more files
[sources.apache_logs]
  type         = "file"
  include      = ["/mia/vector/inlog/rick.log"]    # supports globbing
  ignore_older = 86400                         # 1 day

[sinks.out]
    inputs = ["apache_logs","in"]
    type = "console"

[sinks.backups]
  type = "tcp"
  address = "127.0.0.1:6379"
  inputs = ["apache_logs"]

[sinks.backups.buffer]
  type = "disk"
  max_size = 5000000000 # 5gb
  when_full = "block"
