# Set global options
data_dir = "/mia/vector-config/data"

[sources.in]
    type = "stdin"

[sinks.out]
    inputs = ["in"]
    type = "console"

[sinks.my_sink_id]
  # REQUIRED - General
  type = "elasticsearch" # must be: "elasticsearch"
  inputs = ["in"]
  host = "http://127.0.0.1:9200"

  # OPTIONAL - General
  doc_type = "_doc" # default
  healthcheck = true # default
  index = "vector-%Y-%m-%d"

  # OPTIONAL - Batching
  batch_size = 10490000 # default, bytes
  batch_timeout = 1 # default, seconds

  # OPTIONAL - Requests
  request_in_flight_limit = 5 # default
  request_timeout_secs = 60 # default, seconds

  # OPTIONAL - Buffer
  [sinks.my_sink_id.buffer]
    type = "memory" # default, enum: "memory" or "disk"
    when_full = "block" # default, enum: "block" or "drop_newest"
    max_size = 104900000 # no default, bytes, relevant when type = "disk"
    num_items = 500 # default, events, relevant when type = "memory"

  # OPTIONAL - Headers
  [sinks.my_sink_id.headers]
    X-Powered-By = "Vector"

  # OPTIONAL - Query
  [sinks.my_sink_id.query]
    X-Powered-By = "Vector"

[sinks.backups]
  type = "tcp"
  address = "127.0.0.1:6379"
  inputs = ["in"]

[sinks.backups.buffer]
  type = "disk"
  max_size = 5000000000 # 5gb
  when_full = "block"
